import Head from "next/head";

import ExperienceInfo from "./components/ExperienceInfo";
import { siteConfig } from "@/constant/config";
import { Progress } from "@/components/ui/Progress";
import { Card, CardContent, CardHeader } from "@/components/ui/Card";
import ProfileInfo from "./components/ProfileInfo";

const PortfolioPage = () => {
  return (
    <>
      <Head>
        <title>Profile - {siteConfig.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div>
        <div className="mx-auto max-w-2xl pt-6 px-4 pb-16 sm:px-6 lg:grid lg:max-w-7xl lg:grid-cols-3 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8 lg:px-8 lg:pb-24 lg:pt-16">
          <div className="lg:col-span-2 lg:col-start-1 lg:border-r lg:border-gray-200 lg:pb-16 lg:pr-8">
            <ProfileInfo />
            <ExperienceInfo />
          </div>


          <div className="mt-4 lg:row-span-3 lg:mt-0">
            <Card>
              <CardHeader>
                <h3 className="text-2xl"><strong>Kelengkapan Profile</strong></h3>
                <Progress value={100} />
              </CardHeader>
            </Card>
          </div>
        </div>
      </div>
    </>
  )
}


export default PortfolioPage;
